

import numpy as np
class Location():
    def __init__(self,name):
        self.name = name
        
    def setChildren(self,leftChild,rightChild):
        self.leftChild = leftChild
        self.rightChild = rightChild
    



GLJ = Location('J')
JSJ = Location('J')
MGD = Location('')
VSK = Location('')
TSB = Location('B')
HPD = Location('')
BLZ = Location('BLZ')
BMQ = Location('')
GDG = Location('')
LST = Location('')
QQQ = Location('')
TMV = Location('')
NPZ = Location('NPZ')
DDH = Location('')
SFQ = Location('')
RNK = Location('')
FRS = Location('')
RST = Location('')
DSM = Location('')
GBN = Location('')
GLH = Location('')
JRD = Location('')
SPV = Location('')
PMD = Location('')
MDV = Location('')
MGG = Location('')
FNX = Location('')
FPH = Location('')
DKP = Location('')
XVH = Location('')
SSP = Location('')
JVR = Location('')
HCX = Location('')
LRX = Location('')
DXN = Location('')
GNT = Location('')
QVF = Location('')
QHQ = Location('')
CHX = Location('')
GQD = Location('')
RMF = Location('')
JHN = Location('')
MBG = Location('')
XJN = Location('')
JNR = Location('')
NXD = Location('')
LSS = Location('')
SQH = Location('')
TLM = Location('')
HTG = Location('')
GGM = Location('')
PVJ = Location('')
PRP = Location('')
CVC = Location('')
RMH = Location('')
MRL = Location('')
VMG = Location('')
DKQ = Location('')
QBD = Location('')
RFV = Location('')
FDN = Location('')
RMV = Location('')
BCJ = Location('')
BMB = Location('B')
DLQ = Location('')
NBL = Location('')
NVG = Location('')
CBX = Location('')
HFJ = Location('')
FMQ = Location('')
DSK = Location('')
TRM = Location('')
XKS = Location('')
LDJ = Location('')
LFP = Location('')
PQS = Location('')
MTA = Location('A')
FMM = Location('')
NJD = Location('')
VQJ = Location('')
PXP = Location('')
JDM = Location('')
BJK = Location('')
MRS = Location('')
RCC = Location('')
XPG = Location('')
JLR = Location('')
KLV = Location('')
JBB = Location('B')
NDP = Location('')
XML = Location('')
TPM = Location('')
DGQ = Location('')
XTL = Location('')
VSH = Location('')
PVG = Location('')
CCQ = Location('')
PLS = Location('')
GMQ = Location('')
PNP = Location('')
JPD = Location('')
PRL = Location('')
NMT = Location('')
DLP = Location('')
NFG = Location('')
BPB = Location('B')
JPL = Location('')
HJG = Location('')
BBK = Location('')
GQL = Location('')
BND = Location('')
VRF = Location('')
PXG = Location('')
FKG = Location('')
NCJ = Location('')
CVM = Location('')
GQN = Location('')
LJQ = Location('')
PFK = Location('')
KLQ = Location('')
QRP = Location('')
LRB = Location('B')
XPP = Location('')
LFD = Location('')
TVK = Location('')
MQD = Location('')
MKJ = Location('')
QLF = Location('')
MPP = Location('')
HQQ = Location('')
NXX = Location('')
JBQ = Location('')
BGB = Location('B')
BRD = Location('')
HCM = Location('')
NKP = Location('')
XJK = Location('')
GPS = Location('')
NCM = Location('')
LSX = Location('')
VLF = Location('')
XFT = Location('')
HLR = Location('')
FFR = Location('')
MRB = Location('B')
TVS = Location('')
KNL = Location('')
PNV = Location('')
HVB = Location('B')
RGX = Location('')
MKB = Location('B')
FKL = Location('')
LXQ = Location('')
CQF = Location('')
BSV = Location('')
SVQ = Location('')
BHD = Location('')
QQB = Location('B')
DCG = Location('')
RRT = Location('')
KDN = Location('')
RHJ = Location('')
LVR = Location('')
NHT = Location('')
PBR = Location('')
GBJ = Location('')
BJB = Location('B')
PQH = Location('')
MPM = Location('')
SGB = Location('B')
XQM = Location('')
TLQ = Location('')
FXP = Location('')
VDG = Location('')
XGV = Location('')
JKP = Location('')
KFQ = Location('')
NHL = Location('')
TRS = Location('')
PMM = Location('')
QMB = Location('B')
MKH = Location('')
NCG = Location('')
DBG = Location('')
GVK = Location('')
KKM = Location('')
HLP = Location('')
GPH = Location('')
XQP = Location('')
HRF = Location('')
BXQ = Location('')
NDR = Location('')
HQR = Location('')
PCS = Location('')
LQB = Location('B')
KKR = Location('')
NGM = Location('')
KLN = Location('')
HRR = Location('')
XSF = Location('')
BTG = Location('')
PBT = Location('')
CPP = Location('')
MLN = Location('')
JRF = Location('')
KHS = Location('')
DDP = Location('')
FGM = Location('')
QJH = Location('')
TNX = Location('')
JVC = Location('')
XPV = Location('')
PCK = Location('')
HRS = Location('')
DKK = Location('')
TJN = Location('')
THT = Location('')
JNB = Location('B')
CRL = Location('')
RVF = Location('')
GQT = Location('')
QGF = Location('')
SCJ = Location('')
SCM = Location('')
KNN = Location('')
PPK = Location('')
LPP = Location('')
RRM = Location('')
DCT = Location('')
PQP = Location('')
NTV = Location('')
XXX = Location('')
BKP = Location('')
BLH = Location('')
SPH = Location('')
CVF = Location('')
XDK = Location('')
NQQ = Location('')
TQF = Location('')
VRX = Location('')
KFX = Location('')
DMN = Location('')
VVF = Location('')
XPN = Location('')
LQC = Location('')
XXT = Location('')
PBB = Location('B')
GKF = Location('')
SNJ = Location('')
FKS = Location('')
BJZ = Location('BJZ')
JSF = Location('')
BFM = Location('')
QSD = Location('')
XSR = Location('')
SVM = Location('')
XXJ = Location('')
KRB = Location('B')
XJD = Location('')
HGN = Location('')
TKF = Location('')
KHB = Location('B')
JFK = Location('')
PMT = Location('')
NBV = Location('')
FMN = Location('')
HPS = Location('')
GLT = Location('')
PSM = Location('')
RSM = Location('')
KVD = Location('')
CSQ = Location('')
PKJ = Location('')
LRJ = Location('')
KFG = Location('')
TPD = Location('')
KBB = Location('B')
XGS = Location('')
RHX = Location('')
QPL = Location('')
BQB = Location('B')
KCL = Location('')
XPH = Location('')
QNA = Location('A')
KVJ = Location('')
QJP = Location('')
QFL = Location('')
KFP = Location('')
QLV = Location('')
TLR = Location('')
NLQ = Location('')
JXD = Location('')
LXP = Location('')
DJS = Location('')
FLS = Location('')
HXL = Location('')
NQX = Location('')
PGR = Location('')
CGD = Location('')
KRQ = Location('')
JSB = Location('B')
MBJ = Location('')
MXQ = Location('')
HMN = Location('')
JTL = Location('')
DKG = Location('')
NJN = Location('')
LTS = Location('')
XNP = Location('')
RTG = Location('')
KNT = Location('')
SFL = Location('')
GXD = Location('')
SMC = Location('')
JCB = Location('B')
DQT = Location('')
TFR = Location('')
HTP = Location('')
JKM = Location('')
LGG = Location('')
NSR = Location('')
QFT = Location('')
SQF = Location('')
SFD = Location('')
SCD = Location('')
CXK = Location('')
LDP = Location('')
CDN = Location('')
HFC = Location('')
LGT = Location('')
VKM = Location('')
HGF = Location('')
VGS = Location('')
MGL = Location('')
FDM = Location('')
FTP = Location('')
TCN = Location('')
NGR = Location('')
NDX = Location('')
GVJ = Location('')
MVF = Location('')
MXJ = Location('')
RNH = Location('')
RPD = Location('')
JKG = Location('')
XNX = Location('')
DRL = Location('')
TCF = Location('')
LCL = Location('')
MJM = Location('')
JJK = Location('')
SPX = Location('')
QLC = Location('')
GPC = Location('')
TJQ = Location('')
HSV = Location('')
JKS = Location('')
XDP = Location('')
JDS = Location('')
TQK = Location('')
BLX = Location('')
KRR = Location('')
XMQ = Location('')
KBG = Location('')
LRR = Location('')
LFV = Location('')
HGD = Location('')
GLB = Location('B')
CMB = Location('B')
TKD = Location('')
BQJ = Location('')
QBT = Location('')
GJQ = Location('')
SGF = Location('')
RMD = Location('')
DDJ = Location('')
HNP = Location('')
FQF = Location('')
PJT = Location('')
RKM = Location('')
VBV = Location('')
RBJ = Location('')
MPG = Location('')
BHR = Location('')
VTP = Location('')
PBQ = Location('')
RMX = Location('')
SMP = Location('')
KBF = Location('')
LSL = Location('')
KRM = Location('')
DHJ = Location('')
XNB = Location('B')
TGJ = Location('')
LHQ = Location('')
GCM = Location('')
MJQ = Location('')
NQF = Location('')
VPL = Location('')
HHX = Location('')
FJL = Location('')
HNH = Location('')
RLK = Location('')
SND = Location('')
CNG = Location('')
VDN = Location('')
BRM = Location('')
VTK = Location('')
MVX = Location('')
TDR = Location('')
SQT = Location('')
TMN = Location('')
GNB = Location('B')
QXP = Location('')
GQK = Location('')
QGX = Location('')
TMX = Location('')
BLD = Location('')
RHC = Location('')
XJC = Location('')
GBH = Location('')
TPT = Location('')
FTF = Location('')
QJG = Location('')
FVR = Location('')
XCA = Location('A')
VMJ = Location('')
NTT = Location('')
DMB = Location('B')
CQR = Location('')
JFR = Location('')
TRQ = Location('')
BXS = Location('')
LLG = Location('')
CBP = Location('')
PFT = Location('')
TNS = Location('')
DHV = Location('')
PPL = Location('')
QND = Location('')
VBL = Location('')
FHM = Location('')
KKT = Location('')
LHS = Location('')
LXL = Location('')
BLT = Location('')
JQG = Location('')
KCS = Location('')
SKX = Location('')
VKN = Location('')
DSL = Location('')
TPJ = Location('')
CKR = Location('')
LKL = Location('')
SMM = Location('')
FSN = Location('')
KMS = Location('')
MTX = Location('')
CHM = Location('')
HRQ = Location('')
QCG = Location('')
TQH = Location('')
JXC = Location('')
JVF = Location('')
TJF = Location('')
XDS = Location('')
KJG = Location('')
CTG = Location('')
BBB = Location('B')
DMH = Location('')
BGX = Location('')
RHF = Location('')
KHJ = Location('')
SCS = Location('')
VFX = Location('')
XLQ = Location('')
HDB = Location('B')
PTG = Location('')
NTR = Location('')
KKL = Location('')
XKH = Location('')
BDS = Location('')
QKG = Location('')
LDS = Location('')
KKV = Location('')
JRQ = Location('')
MNP = Location('')
BTM = Location('')
RPH = Location('')
TQD = Location('')
FQP = Location('')
VFV = Location('')
XSL = Location('')
GKN = Location('')
PBK = Location('')
HPB = Location('B')
MCH = Location('')
KSL = Location('')
TCJ = Location('')
RNF = Location('')
BXA = Location('A')
KVK = Location('')
NGF = Location('')
PJN = Location('')
SFJ = Location('')
CPL = Location('')
MKP = Location('')
RPT = Location('')
PRQ = Location('')
DSR = Location('')
VPB = Location('B')
QLQ = Location('')
FNJ = Location('')
SBH = Location('')
PDC = Location('')
QFP = Location('')
CTL = Location('')
LXS = Location('')
VKF = Location('')
HJL = Location('')
KTK = Location('')
RMK = Location('')
MGT = Location('')
XLN = Location('')
FRQ = Location('')
FMB = Location('B')
NFX = Location('')
LMB = Location('B')
JDG = Location('')
MNJ = Location('')
VMF = Location('')
SRN = Location('')
JCC = Location('')
NGJ = Location('')
XCT = Location('')
FFK = Location('')
NFN = Location('')
GHV = Location('')
HFK = Location('')
MNL = Location('')
BPL = Location('')
LJH = Location('')
FDV = Location('')
PBZ = Location('PBZ')
MSB = Location('B')
GGH = Location('')
MPK = Location('')
VVR = Location('')
NMS = Location('')
NXK = Location('')
BSQ = Location('')
XMX = Location('')
NHF = Location('')
MMC = Location('')
GQP = Location('')
TRH = Location('')
RLV = Location('')
DKN = Location('')
MSX = Location('')
SKN = Location('')
LSK = Location('')
RDD = Location('')
DRD = Location('')
GBS = Location('')
TFQ = Location('')
QGS = Location('')
LJK = Location('')
NCR = Location('')
HJQ = Location('')
JCS = Location('')
KTV = Location('')
MMX = Location('')
HVS = Location('')
XMD = Location('')
VVK = Location('')
FBR = Location('')
XKJ = Location('')
AAA = Location('A')
LCV = Location('')
PPJ = Location('')
DGS = Location('')
PFG = Location('')
HVR = Location('')
QXK = Location('')
BTN = Location('')
DPR = Location('')
KVG = Location('')
GFJ = Location('')
JCK = Location('')
QSM = Location('')
XPR = Location('')
RNB = Location('B')
RHB = Location('B')
PGQ = Location('')
CDH = Location('')
BVJ = Location('')
LTG = Location('')
XJR = Location('')
JCV = Location('')
GDN = Location('')
HNX = Location('')
SFN = Location('')
RGL = Location('')
VCA = Location('A')
ZZZ = Location('ZZZ')
GMK = Location('')
LKV = Location('')
PMZ = Location('PMZ')
KBJ = Location('')
PNQ = Location('')
TPQ = Location('')
SPD = Location('')
XCV = Location('')
BVB = Location('B')
BQL = Location('')
JTS = Location('')
SPP = Location('')
VXT = Location('')
MTL = Location('')
KMN = Location('')
RQC = Location('')
FTM = Location('')
RXT = Location('')
QXR = Location('')
HJR = Location('')
BFS = Location('')
TKX = Location('')
DGV = Location('')
DRG = Location('')
VNX = Location('')
CSC = Location('')
KMQ = Location('')
DVP = Location('')
LDF = Location('')
QFH = Location('')
RTT = Location('')
KXR = Location('')
SMD = Location('')
TMB = Location('B')
KHP = Location('')
TLF = Location('')
FRK = Location('')
KTL = Location('')
GRH = Location('')
QMD = Location('')
KDV = Location('')
LGQ = Location('')
FVL = Location('')
MMT = Location('')
CKP = Location('')
STH = Location('')
QBK = Location('')
CTX = Location('')
HHQ = Location('')
JHV = Location('')
FJC = Location('')
TMG = Location('')
XXG = Location('')
BDH = Location('')
FPQ = Location('')
BKL = Location('')
GKG = Location('')
LVL = Location('')
BNH = Location('')
TBG = Location('')
CQH = Location('')
VXD = Location('')
MGR = Location('')
PDJ = Location('')
HXB = Location('B')
XSM = Location('')
HDR = Location('')
GFQ = Location('')
XKC = Location('')
SBN = Location('')
RSX = Location('')
PVP = Location('')
LDG = Location('')
LXV = Location('')
TKT = Location('')
SHX = Location('')
GRG = Location('')
QQV = Location('')
CNX = Location('')
DMX = Location('')
CRC = Location('')
JXP = Location('')
BJC = Location('')
BFT = Location('')
SKV = Location('')
JDB = Location('B')
XRK = Location('')
FXN = Location('')
JJQ = Location('')
DDN = Location('')
QBH = Location('')
MLT = Location('')
SNC = Location('')
FTN = Location('')
DPL = Location('')
TFS = Location('')
HVQ = Location('')
JJX = Location('')
KVR = Location('')
MQR = Location('')
MDD = Location('')
PCB = Location('B')
NLT = Location('')
GBD = Location('')
NHV = Location('')
GHT = Location('')
SDQ = Location('')
TRJ = Location('')
HGC = Location('')
MHQ = Location('')
CKX = Location('')
SQM = Location('')
PQG = Location('')
JRL = Location('')
NRG = Location('')
GHD = Location('')
LBF = Location('')
MKK = Location('')
CPG = Location('')
SQB = Location('B')
VKQ = Location('')
KFK = Location('')
PJR = Location('')
FXH = Location('')
JPQ = Location('')
PDB = Location('B')
JKX = Location('')
DTB = Location('B')
VCG = Location('')
KVM = Location('')
QXS = Location('')
CJK = Location('')
PKP = Location('')
JMG = Location('')
FRX = Location('')
KFF = Location('')
DPB = Location('B')
SCB = Location('B')
DHN = Location('')
QLH = Location('')
PMX = Location('')
XMK = Location('')
NDB = Location('B')
LQS = Location('')
PGG = Location('')


GLJ.setChildren(QQV, JTL)
JSJ.setChildren(DKN, GQN)
MGD.setChildren(BPL, LQC)
VSK.setChildren(SPH, DDH)
TSB.setChildren(MKP, TKX)
HPD.setChildren(GKG, XMX)
BLZ.setChildren(HGN, KRR)
BMQ.setChildren(JXC, HFC)
GDG.setChildren(BVJ, NBL)
LST.setChildren(PVJ, DPR)
QQQ.setChildren(RLV, SNJ)
TMV.setChildren(XGV, KCL)
NPZ.setChildren(JRD, NHL)
DDH.setChildren(NDR, XPN)
SFQ.setChildren(TKD, SQH)
RNK.setChildren(TJN, NFX)
FRS.setChildren(SCJ, FDV)
RST.setChildren(BSQ, MHQ)
DSM.setChildren(FRX, DMN)
GBN.setChildren(VBL, XRK)
GLH.setChildren(KNN, PKP)
JRD.setChildren(LDP, RNH)
SPV.setChildren(JNR, FRK)
PMD.setChildren(FXP, BKL)
MDV.setChildren(MGD, FHM)
MGG.setChildren(KMN, QPL)
FNX.setChildren(FKG, NLT)
FPH.setChildren(QXS, PBR)
DKP.setChildren(QFT, QQQ)
XVH.setChildren(PVP, GBJ)
SSP.setChildren(BHD, KRM)
JVR.setChildren(RHB, LDJ)
HCX.setChildren(RNK, LGT)
LRX.setChildren(SFN, GXD)
DXN.setChildren(NQX, KNL)
GNT.setChildren(GHV, DKG)
QVF.setChildren(NJN, FSN)
QHQ.setChildren(FXN, PNP)
CHX.setChildren(DHN, BQB)
GQD.setChildren(TLQ, XXG)
RMF.setChildren(RVF, KKR)
JHN.setChildren(NRG, RCC)
MBG.setChildren(XPV, MSB)
XJN.setChildren(SQT, XXJ)
JNR.setChildren(VTP, XSF)
NXD.setChildren(DKP, MKJ)
LSS.setChildren(KHS, BSV)
SQH.setChildren(BLH, VCG)
TLM.setChildren(DCG, BQL)
HTG.setChildren(TLF, KRB)
GGM.setChildren(KLV, PTG)
PVJ.setChildren(BHR, TRH)
PRP.setChildren(QLC, JPQ)
CVC.setChildren(KVJ, FTM)
RMH.setChildren(RPD, FFK)
MRL.setChildren(KFK, LJK)
VMG.setChildren(LSX, FPH)
DKQ.setChildren(XSM, CXK)
QBD.setChildren(BGB, GPS)
RFV.setChildren(QCG, NJD)
FDN.setChildren(QFL, DXN)
RMV.setChildren(NCJ, PMZ)
BCJ.setChildren(MDD, TMG)
BMB.setChildren(GLH, MKK)
DLQ.setChildren(JKX, VGS)
NBL.setChildren(GFQ, PRQ)
NVG.setChildren(SCS, JTS)
CBX.setChildren(MXQ, QSM)
HFJ.setChildren(NXX, VRX)
FMQ.setChildren(KDV, HFJ)
DSK.setChildren(BND, GFJ)
TRM.setChildren(MMX, BTG)
XKS.setChildren(GXD, SFN)
LDJ.setChildren(TFQ, CJK)
LFP.setChildren(TFS, LST)
PQS.setChildren(PJR, SMD)
MTA.setChildren(JPD, MVX)
FMM.setChildren(GPC, BVB)
NJD.setChildren(JMG, DPL)
VQJ.setChildren(KRM, BHD)
PXP.setChildren(BPB, JJK)
JDM.setChildren(HHQ, JXD)
BJK.setChildren(SRN, DRL)
MRS.setChildren(RPT, SQF)
RCC.setChildren(DRD, SPP)
XPG.setChildren(XRK, VBL)
JLR.setChildren(LJQ, XDP)
KLV.setChildren(SKX, SKX)
JBB.setChildren(LRB, RRT)
NDP.setChildren(KMS, DDJ)
XML.setChildren(TPD, VKQ)
TPM.setChildren(PKJ, PGR)
DGQ.setChildren(JFK, TMB)
XTL.setChildren(MPK, CTL)
VSH.setChildren(BNH, HJR)
PVG.setChildren(SPV, KCS)
CCQ.setChildren(LQB, VTK)
PLS.setChildren(HPS, CVC)
GMQ.setChildren(CTG, QHQ)
PNP.setChildren(VSK, JCV)
JPD.setChildren(KKV, FQP)
PRL.setChildren(KRB, TLF)
NMT.setChildren(HXL, NHV)
DLP.setChildren(KXR, BXQ)
NFG.setChildren(DSR, HNX)
BPB.setChildren(BTM, MGR)
JPL.setChildren(NMT, QMD)
HJG.setChildren(XJD, HHX)
BBK.setChildren(VVF, SBN)
GQL.setChildren(XNX, CKR)
BND.setChildren(SQB, KFG)
VRF.setChildren(JKS, LGG)
PXG.setChildren(QMD, NMT)
FKG.setChildren(GBS, JLR)
NCJ.setChildren(NFG, CQH)
CVM.setChildren(LFD, NPZ)
GQN.setChildren(SMM, PQH)
LJQ.setChildren(LXQ, KVG)
PFK.setChildren(HHQ, JXD)
KLQ.setChildren(JNB, DKQ)
QRP.setChildren(SCB, HCM)
LRB.setChildren(RMD, KLN)
XPP.setChildren(GMK, LKL)
LFD.setChildren(NHL, JRD)
TVK.setChildren(TMV, TJF)
MQD.setChildren(HTG, PRL)
MKJ.setChildren(QQQ, QFT)
QLF.setChildren(CHX, XSR)
MPP.setChildren(XMK, QFP)
HQQ.setChildren(PCS, PDC)
NXX.setChildren(BTN, KBJ)
JBQ.setChildren(GGH, FJL)
BGB.setChildren(JSF, MNP)
BRD.setChildren(VMF, NTR)
HCM.setChildren(RHX, KJG)
NKP.setChildren(GHV, DKG)
XJK.setChildren(TRS, DGQ)
GPS.setChildren(MNP, JSF)
NCM.setChildren(VMJ, CSC)
LSX.setChildren(PBR, QXS)
VLF.setChildren(MTL, GVK)
XFT.setChildren(XGS, CRL)
HLR.setChildren(FMM, QLH)
FFR.setChildren(XXX, BGX)
MRB.setChildren(XJD, HHX)
TVS.setChildren(MTL, GVK)
KNL.setChildren(KDN, HQQ)
PNV.setChildren(SQF, RPT)
HVB.setChildren(BBB, LLG)
RGX.setChildren(RLK, MSX)
MKB.setChildren(HNP, NGM)
FKL.setChildren(XMK, QFP)
LXQ.setChildren(GNB, TQH)
CQF.setChildren(NGF, NQF)
BSV.setChildren(KFX, HNH)
SVQ.setChildren(PXP, XQM)
BHD.setChildren(XVH, GDN)
QQB.setChildren(PCB, PCB)
DCG.setChildren(GRH, RGX)
RRT.setChildren(KLN, RMD)
KDN.setChildren(PDC, PCS)
RHJ.setChildren(VTK, LQB)
LVR.setChildren(VSH, QGS)
NHT.setChildren(LQS, DMB)
PBR.setChildren(TCF, JCC)
GBJ.setChildren(MLT, XNB)
BJB.setChildren(XPR, MBG)
PQH.setChildren(MCH, LMB)
MPM.setChildren(BSV, KHS)
SGB.setChildren(TKF, PMD)
XQM.setChildren(JJK, BPB)
TLQ.setChildren(FGM, CRC)
FXP.setChildren(BCJ, TDR)
VDG.setChildren(VMJ, CSC)
XGV.setChildren(LHS, LTS)
JKP.setChildren(PXG, JPL)
KFQ.setChildren(TSB, RNB)
NHL.setChildren(LDP, RNH)
TRS.setChildren(JFK, TMB)
PMM.setChildren(RHC, KMQ)
QMB.setChildren(PPJ, CNG)
MKH.setChildren(DDJ, KMS)
NCG.setChildren(XXX, BGX)
DBG.setChildren(SND, HMN)
GVK.setChildren(TQD, JHN)
KKM.setChildren(KKL, PBT)
HLP.setChildren(JPQ, QLC)
GPH.setChildren(JKG, DKK)
XQP.setChildren(GLH, MKK)
HRF.setChildren(BGB, GPS)
BXQ.setChildren(BDH, GQT)
NDR.setChildren(KKM, LRR)
HQR.setChildren(RGL, RMX)
PCS.setChildren(DTB, LDS)
LQB.setChildren(GMQ, HRQ)
KKR.setChildren(KTV, CMB)
NGM.setChildren(KFQ, BQJ)
KLN.setChildren(XFT, JRL)
HRR.setChildren(RHJ, CCQ)
XSF.setChildren(CKX, PLS)
BTG.setChildren(GDG, JDS)
PBT.setChildren(NVG, DVP)
CPP.setChildren(VSH, QGS)
MLN.setChildren(VGS, JKX)
JRF.setChildren(SKN, RMF)
KHS.setChildren(KFX, HNH)
DDP.setChildren(QJG, XKJ)
FGM.setChildren(TVK, TNS)
QJH.setChildren(XSL, QXP)
TNX.setChildren(NBV, KLQ)
JVC.setChildren(FBR, PFT)
XPV.setChildren(TLM, PPK)
PCK.setChildren(KBG, TGJ)
HRS.setChildren(VKM, JVF)
DKK.setChildren(NHT, ZZZ)
TJN.setChildren(KTL, QLF)
THT.setChildren(JJQ, LRJ)
JNB.setChildren(CXK, XSM)
CRL.setChildren(VXT, TBG)
RVF.setChildren(CMB, KTV)
GQT.setChildren(PBB, CVM)
QGF.setChildren(MGT, SKV)
SCJ.setChildren(CQF, KRQ)
SCM.setChildren(DPB, PMM)
KNN.setChildren(XLQ, VPB)
PPK.setChildren(BQL, DCG)
LPP.setChildren(HJG, MRB)
RRM.setChildren(RXT, PBZ)
DCT.setChildren(FTF, HVB)
PQP.setChildren(PBQ, HVR)
NTV.setChildren(SCM, GKN)
XXX.setChildren(LSS, MPM)
BKP.setChildren(LXL, LXL)
BLH.setChildren(QLV, SFJ)
SPH.setChildren(NDR, XPN)
CVF.setChildren(KDV, HFJ)
XDK.setChildren(RHJ, CCQ)
NQQ.setChildren(NTT, FVL)
TQF.setChildren(XCV, NDX)
VRX.setChildren(BTN, KBJ)
KFX.setChildren(XLN, FDN)
DMN.setChildren(TPT, JRQ)
VVF.setChildren(TPQ, CDH)
XPN.setChildren(LRR, KKM)
LQC.setChildren(TMX, LHQ)
XXT.setChildren(TLR, DDP)
PBB.setChildren(LFD, LFD)
GKF.setChildren(CHM, XTL)
SNJ.setChildren(NSR, KVD)
FKS.setChildren(PPL, PSM)
BJZ.setChildren(MVX, JPD)
JSF.setChildren(GQD, GQP)
BFM.setChildren(QXR, MVF)
QSD.setChildren(JHV, JKP)
XSR.setChildren(DHN, BQB)
SVM.setChildren(PKJ, PGR)
XXJ.setChildren(HGF, MPG)
KRB.setChildren(QMB, VNX)
XJD.setChildren(SFQ, SGF)
HGN.setChildren(KBF, LXS)
TKF.setChildren(FXP, BKL)
KHB.setChildren(TPJ, CGD)
JFK.setChildren(JJX, DMH)
PMT.setChildren(HGC, HJQ)
NBV.setChildren(DKQ, JNB)
FMN.setChildren(BJB, HSV)
HPS.setChildren(KVJ, KVJ)
GLT.setChildren(LXL, NFN)
PSM.setChildren(PMT, CKP)
RSM.setChildren(JRF, PDB)
KVD.setChildren(PFK, JDM)
CSQ.setChildren(HJG, MRB)
PKJ.setChildren(HDR, TJQ)
LRJ.setChildren(JSJ, BFS)
KFG.setChildren(KKT, CQR)
TPD.setChildren(THT, KBB)
KBB.setChildren(LRJ, JJQ)
XGS.setChildren(VXT, TBG)
RHX.setChildren(XJK, QND)
QPL.setChildren(DDN, STH)
BQB.setChildren(XJC, SBH)
KCL.setChildren(LHS, LTS)
XPH.setChildren(KXR, BXQ)
QNA.setChildren(NHL, JRD)
KVJ.setChildren(KHJ, KHJ)
QJP.setChildren(RNK, LGT)
QFL.setChildren(KNL, NQX)
KFP.setChildren(HLR, LCV)
QLV.setChildren(PMX, BJK)
TLR.setChildren(QJG, XKJ)
NLQ.setChildren(XML, BDS)
JXD.setChildren(MQD, GBH)
LXP.setChildren(HRR, XDK)
DJS.setChildren(GLJ, RNF)
FLS.setChildren(FMB, MRL)
HXL.setChildren(BXS, FDM)
NQX.setChildren(KDN, HQQ)
PGR.setChildren(TJQ, HDR)
CGD.setChildren(DGS, VKN)
KRQ.setChildren(NQF, NGF)
JSB.setChildren(PNQ, DHV)
MBJ.setChildren(JCK, QRP)
MXQ.setChildren(DRG, DSM)
HMN.setChildren(CBP, CPG)
JTL.setChildren(RST, SPD)
DKG.setChildren(GQK, XMQ)
NJN.setChildren(TVS, VLF)
LTS.setChildren(JCB, TQF)
XNP.setChildren(JVF, VKM)
RTG.setChildren(XXJ, SQT)
KNT.setChildren(LRB, RRT)
SFL.setChildren(LXP, CDN)
GXD.setChildren(MMT, CNX)
SMC.setChildren(XTL, CHM)
JCB.setChildren(XCV, NDX)
DQT.setChildren(RBJ, QGF)
TFR.setChildren(MKH, NDP)
HTP.setChildren(CSQ, LPP)
JKM.setChildren(VVK, SHX)
LGG.setChildren(RPH, NTV)
NSR.setChildren(JDM, PFK)
QFT.setChildren(SNJ, RLV)
SQF.setChildren(GRG, RSX)
SFD.setChildren(FFK, RPD)
SCD.setChildren(SNC, LGQ)
CXK.setChildren(VDN, SQM)
LDP.setChildren(NLQ, DGV)
CDN.setChildren(XDK, HRR)
HFC.setChildren(QBD, HRF)
LGT.setChildren(NFX, TJN)
VKM.setChildren(QJP, HCX)
HGF.setChildren(SCD, TKT)
VGS.setChildren(SGB, VXD)
MGL.setChildren(FTN, LBF)
FDM.setChildren(DLQ, MLN)
FTP.setChildren(HJL, JQG)
TCN.setChildren(MRL, FMB)
NGR.setChildren(QPL, KMN)
NDX.setChildren(DMX, LTG)
GVJ.setChildren(JDG, PCK)
MVF.setChildren(KVR, TQK)
MXJ.setChildren(FPQ, VBV)
RNH.setChildren(DGV, NLQ)
RPD.setChildren(RFV, PGG)
JKG.setChildren(NHT, NHT)
XNX.setChildren(JDB, DQT)
DRL.setChildren(GCM, DSK)
TCF.setChildren(TCJ, SVQ)
LCL.setChildren(NJN, FSN)
MJM.setChildren(QSM, MXQ)
JJK.setChildren(BTM, MGR)
SPX.setChildren(JDG, PCK)
QLC.setChildren(DHJ, PVG)
GPC.setChildren(XKC, RTT)
TJQ.setChildren(XPG, GBN)
HSV.setChildren(XPR, MBG)
JKS.setChildren(RPH, NTV)
XDP.setChildren(KVG, LXQ)
JDS.setChildren(NBL, BVJ)
TQK.setChildren(NCR, HTP)
BLX.setChildren(TFS, LST)
KRR.setChildren(LXS, KBF)
XMQ.setChildren(KHB, MMC)
KBG.setChildren(DBG, MQR)
LRR.setChildren(KKL, PBT)
LFV.setChildren(HVQ, MNJ)
HGD.setChildren(MNL, PDJ)
GLB.setChildren(NDP, MKH)
CMB.setChildren(VDG, NCM)
TKD.setChildren(VCG, BLH)
BQJ.setChildren(TSB, RNB)
QBT.setChildren(MKB, RKM)
GJQ.setChildren(BTG, MMX)
SGF.setChildren(TKD, SQH)
RMD.setChildren(JRL, XFT)
DDJ.setChildren(HRS, XNP)
HNP.setChildren(KFQ, BQJ)
FQF.setChildren(MNJ, HVQ)
PJT.setChildren(FRQ, KFP)
RKM.setChildren(NGM, HNP)
VBV.setChildren(LVR, CPP)
RBJ.setChildren(SKV, MGT)
MPG.setChildren(SCD, TKT)
BHR.setChildren(BRM, FJC)
VTP.setChildren(CKX, PLS)
PBQ.setChildren(RQC, HGD)
RMX.setChildren(FTP, NGJ)
SMP.setChildren(KRR, HGN)
KBF.setChildren(RMK, BMQ)
LSL.setChildren(JSB, VPL)
KRM.setChildren(GDN, XVH)
DHJ.setChildren(SPV, KCS)
XNB.setChildren(QFH, PGQ)
TGJ.setChildren(DBG, MQR)
LHQ.setChildren(FNX, KFF)
GCM.setChildren(GFJ, BND)
MJQ.setChildren(BBK, KVM)
NQF.setChildren(SSP, VQJ)
VPL.setChildren(DHV, PNQ)
HHX.setChildren(SFQ, SGF)
FJL.setChildren(MGL, XKH)
HNH.setChildren(FDN, XLN)
RLK.setChildren(LCL, QVF)
SND.setChildren(CPG, CBP)
CNG.setChildren(DJS, HVS)
VDN.setChildren(QBK, MXJ)
BRM.setChildren(SMC, GKF)
VTK.setChildren(HRQ, GMQ)
MVX.setChildren(KKV, FQP)
TDR.setChildren(TMG, MDD)
SQT.setChildren(HGF, MPG)
TMN.setChildren(HVB, FTF)
GNB.setChildren(BFT, QXK)
QXP.setChildren(MJM, CBX)
GQK.setChildren(MMC, KHB)
QGX.setChildren(NDB, QSD)
TMX.setChildren(FNX, KFF)
BLD.setChildren(NBV, KLQ)
RHC.setChildren(NXK, PJT)
XJC.setChildren(QKG, QKG)
GBH.setChildren(HTG, PRL)
TPT.setChildren(TRQ, XXT)
FTF.setChildren(BBB, LLG)
QJG.setChildren(FKS, PQG)
FVR.setChildren(LXP, CDN)
XCA.setChildren(FVR, SFL)
VMJ.setChildren(KHP, MDV)
NTT.setChildren(LFP, BLX)
DMB.setChildren(TCN, FLS)
CQR.setChildren(LRX, XKS)
JFR.setChildren(TMN, DCT)
TRQ.setChildren(DDP, TLR)
BXS.setChildren(MLN, DLQ)
LLG.setChildren(LSK, XMD)
CBP.setChildren(RHF, BRD)
PFT.setChildren(SMP, BLZ)
TNS.setChildren(TMV, TJF)
DHV.setChildren(VFX, VVR)
PPL.setChildren(CKP, PMT)
QND.setChildren(DGQ, TRS)
VBL.setChildren(MGG, NGR)
FHM.setChildren(BPL, LQC)
KKT.setChildren(LRX, XKS)
LHS.setChildren(JCB, TQF)
LXL.setChildren(LJH, LJH)
BLT.setChildren(GGH, FJL)
JQG.setChildren(XCT, FRS)
KCS.setChildren(JNR, FRK)
SKX.setChildren(JKG, JKG)
VKN.setChildren(NMS, QBT)
DSL.setChildren(FMN, PJN)
TPJ.setChildren(VKN, DGS)
CKR.setChildren(JDB, DQT)
LKL.setChildren(QLQ, NXD)
SMM.setChildren(LMB, MCH)
FSN.setChildren(TVS, VLF)
KMS.setChildren(XNP, HRS)
MTX.setChildren(LGG, JKS)
CHM.setChildren(CTL, MPK)
HRQ.setChildren(QHQ, CTG)
QCG.setChildren(JMG, DPL)
TQH.setChildren(QXK, BFT)
JXC.setChildren(QBD, HRF)
JVF.setChildren(QJP, HCX)
TJF.setChildren(KCL, XGV)
XDS.setChildren(QQB, QQB)
KJG.setChildren(QND, XJK)
CTG.setChildren(FXN, PNP)
BBB.setChildren(LSK, XMD)
DMH.setChildren(NHF, JKM)
BGX.setChildren(LSS, MPM)
RHF.setChildren(VMF, NTR)
KHJ.setChildren(JPD, MVX)
SCS.setChildren(FNJ, RSM)
VFX.setChildren(LXV, XPP)
XLQ.setChildren(RMH, SFD)
HDB.setChildren(HVR, PBQ)
PTG.setChildren(SKX, GPH)
NTR.setChildren(LDG, LKV)
KKL.setChildren(NVG, DVP)
XKH.setChildren(FTN, LBF)
BDS.setChildren(TPD, VKQ)
QKG.setChildren(FBR, FBR)
LDS.setChildren(HQR, BJC)
KKV.setChildren(MPP, FKL)
JRQ.setChildren(TRQ, XXT)
MNP.setChildren(GQP, GQD)
BTM.setChildren(GJQ, TRM)
RPH.setChildren(GKN, SCM)
TQD.setChildren(RCC, NRG)
FQP.setChildren(FKL, MPP)
VFV.setChildren(QQB, HPB)
XSL.setChildren(CBX, MJM)
GKN.setChildren(DPB, PMM)
PBK.setChildren(QBH, GQL)
HPB.setChildren(PCB, RRM)
MCH.setChildren(RTG, XJN)
KSL.setChildren(FVL, NTT)
TCJ.setChildren(PXP, XQM)
RNF.setChildren(JTL, QQV)
BXA.setChildren(NFG, CQH)
KVK.setChildren(PRP, HLP)
NGF.setChildren(SSP, VQJ)
PJN.setChildren(BJB, HSV)
SFJ.setChildren(BJK, PMX)
CPL.setChildren(LDJ, RHB)
MKP.setChildren(TRJ, BFM)
RPT.setChildren(GRG, RSX)
PRQ.setChildren(XPH, DLP)
DSR.setChildren(KNT, JBB)
VPB.setChildren(RMH, SFD)
QLQ.setChildren(MKJ, DKP)
FNJ.setChildren(PDB, JRF)
SBH.setChildren(QKG, JVC)
PDC.setChildren(LDS, DTB)
QFP.setChildren(MJQ, HFK)
CTL.setChildren(RDD, KVK)
LXS.setChildren(BMQ, RMK)
VKF.setChildren(QBH, GQL)
HJL.setChildren(XCT, FRS)
KTK.setChildren(LDF, HPD)
RMK.setChildren(HFC, JXC)
MGT.setChildren(JFR, HXB)
XLN.setChildren(QFL, DXN)
FRQ.setChildren(HLR, LCV)
FMB.setChildren(KFK, LJK)
NFX.setChildren(KTL, QLF)
LMB.setChildren(RTG, XJN)
JDG.setChildren(TGJ, KBG)
MNJ.setChildren(GVJ, SPX)
VMF.setChildren(LDG, LKV)
SRN.setChildren(GCM, DSK)
JCC.setChildren(SVQ, TCJ)
NGJ.setChildren(HJL, JQG)
XCT.setChildren(SCJ, FDV)
FFK.setChildren(RFV, PGG)
NFN.setChildren(LJH, RMV)
GHV.setChildren(GQK, XMQ)
HFK.setChildren(KVM, BBK)
MNL.setChildren(GLB, TFR)
BPL.setChildren(LHQ, TMX)
LJH.setChildren(NCJ, NCJ)
FDV.setChildren(CQF, KRQ)
PBZ.setChildren(SFL, FVR)
MSB.setChildren(PPK, TLM)
GGH.setChildren(XKH, MGL)
MPK.setChildren(KVK, RDD)
VVR.setChildren(XPP, LXV)
NMS.setChildren(MKB, RKM)
NXK.setChildren(FRQ, KFP)
BSQ.setChildren(JCS, MBJ)
XMX.setChildren(DSL, CTX)
NHF.setChildren(VVK, SHX)
MMC.setChildren(CGD, TPJ)
GQP.setChildren(TLQ, XXG)
TRH.setChildren(FJC, BRM)
RLV.setChildren(NSR, KVD)
DKN.setChildren(PQH, SMM)
MSX.setChildren(LCL, QVF)
SKN.setChildren(KKR, RVF)
LSK.setChildren(PNV, MRS)
RDD.setChildren(PRP, HLP)
DRD.setChildren(JBQ, BLT)
GBS.setChildren(XDP, LJQ)
TFQ.setChildren(BLD, TNX)
QGS.setChildren(BNH, HJR)
LJK.setChildren(CVF, FMQ)
NCR.setChildren(CSQ, LPP)
HJQ.setChildren(SVM, TPM)
JCS.setChildren(QRP, JCK)
KTV.setChildren(VDG, NCM)
MMX.setChildren(GDG, JDS)
HVS.setChildren(GLJ, RNF)
XMD.setChildren(PNV, MRS)
VVK.setChildren(XDS, VFV)
FBR.setChildren(SMP, SMP)
XKJ.setChildren(PQG, FKS)
AAA.setChildren(LQS, DMB)
LCV.setChildren(FMM, QLH)
PPJ.setChildren(HVS, DJS)
DGS.setChildren(QBT, NMS)
PFG.setChildren(LDF, HPD)
HVR.setChildren(RQC, HGD)
QXK.setChildren(BMB, XQP)
BTN.setChildren(GHD, JXP)
DPR.setChildren(TRH, BHR)
KVG.setChildren(GNB, TQH)
GFJ.setChildren(KFG, SQB)
JCK.setChildren(SCB, HCM)
QSM.setChildren(DRG, DSM)
XPR.setChildren(XPV, MSB)
RNB.setChildren(TKX, MKP)
RHB.setChildren(TFQ, CJK)
PGQ.setChildren(VRF, MTX)
CDH.setChildren(GNT, NKP)
BVJ.setChildren(PRQ, GFQ)
LTG.setChildren(QGX, LVL)
XJR.setChildren(QXP, XSL)
JCV.setChildren(SPH, DDH)
GDN.setChildren(PVP, GBJ)
HNX.setChildren(KNT, JBB)
SFN.setChildren(MMT, CNX)
RGL.setChildren(FTP, NGJ)
VCA.setChildren(KRR, HGN)
ZZZ.setChildren(DMB, LQS)
GMK.setChildren(QLQ, NXD)
LKV.setChildren(VMG, SDQ)
PMZ.setChildren(CQH, NFG)
KBJ.setChildren(GHD, JXP)
PNQ.setChildren(VFX, VVR)
TPQ.setChildren(GNT, NKP)
SPD.setChildren(MHQ, BSQ)
XCV.setChildren(DMX, LTG)
BVB.setChildren(XKC, RTT)
BQL.setChildren(RGX, GRH)
JTS.setChildren(RSM, FNJ)
SPP.setChildren(BLT, JBQ)
VXT.setChildren(CPL, JVR)
MTL.setChildren(JHN, TQD)
KMN.setChildren(DDN, STH)
RQC.setChildren(PDJ, MNL)
FTM.setChildren(KHJ, BJZ)
RXT.setChildren(FVR, SFL)
QXR.setChildren(KVR, TQK)
HJR.setChildren(QJH, XJR)
BFS.setChildren(GQN, DKN)
TKX.setChildren(BFM, TRJ)
DGV.setChildren(BDS, XML)
DRG.setChildren(FRX, DMN)
VNX.setChildren(CNG, PPJ)
CSC.setChildren(MDV, KHP)
KMQ.setChildren(PJT, NXK)
DVP.setChildren(SCS, JTS)
LDF.setChildren(XMX, GKG)
QFH.setChildren(MTX, VRF)
RTT.setChildren(PQS, GBD)
KXR.setChildren(BDH, BDH)
SMD.setChildren(GHT, GGM)
TMB.setChildren(DMH, JJX)
KHP.setChildren(FHM, MGD)
TLF.setChildren(QMB, VNX)
FRK.setChildren(VTP, XSF)
KTL.setChildren(CHX, XSR)
GRH.setChildren(RLK, MSX)
QMD.setChildren(NHV, HXL)
KDV.setChildren(VRX, NXX)
LGQ.setChildren(VKF, PBK)
FVL.setChildren(BLX, LFP)
MMT.setChildren(NQQ, KSL)
CKP.setChildren(HJQ, HGC)
STH.setChildren(BKP, GLT)
QBK.setChildren(FPQ, VBV)
CTX.setChildren(FMN, PJN)
HHQ.setChildren(GBH, MQD)
JHV.setChildren(PXG, JPL)
FJC.setChildren(GKF, SMC)
TMG.setChildren(PFG, KTK)
XXG.setChildren(CRC, FGM)
BDH.setChildren(PBB, PBB)
FPQ.setChildren(CPP, LVR)
BKL.setChildren(BCJ, TDR)
GKG.setChildren(DSL, CTX)
LVL.setChildren(NDB, QSD)
BNH.setChildren(QJH, XJR)
TBG.setChildren(JVR, CPL)
CQH.setChildren(HNX, DSR)
VXD.setChildren(TKF, PMD)
MGR.setChildren(TRM, GJQ)
PDJ.setChildren(GLB, TFR)
HXB.setChildren(DCT, TMN)
XSM.setChildren(SQM, VDN)
HDR.setChildren(XPG, GBN)
GFQ.setChildren(XPH, DLP)
XKC.setChildren(PQS, GBD)
SBN.setChildren(TPQ, CDH)
RSX.setChildren(LFV, FQF)
PVP.setChildren(XNB, MLT)
LDG.setChildren(VMG, SDQ)
LXV.setChildren(LKL, GMK)
TKT.setChildren(SNC, LGQ)
SHX.setChildren(XDS, VFV)
GRG.setChildren(FQF, LFV)
QQV.setChildren(RST, SPD)
CNX.setChildren(NQQ, KSL)
DMX.setChildren(LVL, QGX)
CRC.setChildren(TVK, TNS)
JXP.setChildren(FFR, NCG)
BJC.setChildren(RGL, RMX)
BFT.setChildren(XQP, BMB)
SKV.setChildren(JFR, HXB)
JDB.setChildren(QGF, RBJ)
XRK.setChildren(NGR, MGG)
FXN.setChildren(JCV, VSK)
JJQ.setChildren(JSJ, BFS)
DDN.setChildren(BKP, GLT)
QBH.setChildren(XNX, CKR)
MLT.setChildren(PGQ, QFH)
SNC.setChildren(VKF, PBK)
FTN.setChildren(HDB, PQP)
DPL.setChildren(LSL, FXH)
TFS.setChildren(DPR, PVJ)
HVQ.setChildren(SPX, GVJ)
JJX.setChildren(NHF, JKM)
KVR.setChildren(HTP, NCR)
MQR.setChildren(SND, HMN)
MDD.setChildren(PFG, KTK)
PCB.setChildren(RXT, RXT)
NLT.setChildren(GBS, JLR)
GBD.setChildren(SMD, PJR)
NHV.setChildren(BXS, FDM)
GHT.setChildren(KLV, PTG)
SDQ.setChildren(LSX, FPH)
TRJ.setChildren(QXR, MVF)
HGC.setChildren(TPM, SVM)
MHQ.setChildren(JCS, MBJ)
CKX.setChildren(HPS, HPS)
SQM.setChildren(MXJ, QBK)
PQG.setChildren(PPL, PSM)
JRL.setChildren(CRL, XGS)
NRG.setChildren(DRD, SPP)
GHD.setChildren(NCG, FFR)
LBF.setChildren(PQP, HDB)
MKK.setChildren(KNN, PKP)
CPG.setChildren(RHF, BRD)
SQB.setChildren(KKT, CQR)
VKQ.setChildren(THT, KBB)
KFK.setChildren(FMQ, CVF)
PJR.setChildren(GHT, GGM)
FXH.setChildren(JSB, VPL)
JPQ.setChildren(PVG, DHJ)
PDB.setChildren(SKN, RMF)
JKX.setChildren(VXD, SGB)
DTB.setChildren(HQR, BJC)
VCG.setChildren(QLV, SFJ)
KVM.setChildren(SBN, VVF)
QXS.setChildren(TCF, JCC)
CJK.setChildren(BLD, TNX)
PKP.setChildren(VPB, XLQ)
JMG.setChildren(LSL, FXH)
FRX.setChildren(JRQ, TPT)
KFF.setChildren(FKG, NLT)
DPB.setChildren(RHC, KMQ)
SCB.setChildren(KJG, RHX)
DHN.setChildren(XJC, SBH)
QLH.setChildren(GPC, BVB)
PMX.setChildren(DRL, SRN)
XMK.setChildren(HFK, MJQ)
NDB.setChildren(JHV, JKP)
LQS.setChildren(TCN, FLS)
PGG.setChildren(NJD, QCG)
'''


AAA = Location("AAA")
BBB = Location("BBB")
BBC = Location("BBC")
AAB = Location("AAB")
AAZ = Location("AAZ")
BBA = Location("BBA")
BBZ = Location("BBZ")
XXX = Location("XXX")


AAA.setChildren(AAB, XXX)
AAB.setChildren(XXX, AAZ)
AAZ.setChildren(AAB, XXX)
BBA.setChildren(BBB, XXX)
BBB.setChildren(BBC, BBC)
BBC.setChildren(BBZ, BBZ)
BBZ.setChildren(BBB, BBB)
XXX.setChildren(XXX, XXX)
path = "LR"
'''
myLoc1 = AAA
myLoc2 = VCA
steps1 = 0
steps2 = 0

myLoc3 = BXA
myLoc4 = XCA
myLoc5 = QNA
myLoc6 = MTA
steps3 = 0
steps4 = 0
steps5 = 0
steps6 = 0
path = "LRRLLRLRRRLRRRLRRLRRRLRRLRRRLRRLRRRLRLRRRLRRRLRRRLRLRRLRRRLRRRLRRLRRLRRLRLLLRRRLRRRLRLRLRRLLRRRLRRLRRRLRLRRLRRRLRRRLLRLRLLRRRLRRRLLRRRLRRRLRRRLRRLRRRLLLRRRLRLLLRLRLRLLRLRLLLRRLRRLLRRLRRRLRRLRRLRLRRLLRRLRLRRLLLRRRLLRRRLLRLRLLRRRLRLLRRLRLRRLRLRRRLLRRRLLRRLRLRRLRRLLRLRLRRRLRLRRRR"



while(not(myLoc1.name == "ZZZ" or myLoc1.name == "PMZ" or myLoc1.name == "BLZ" or myLoc1.name == "NPZ" or myLoc1.name == "BJZ" or myLoc1.name == "PBZ")):
    journey = steps1%len(path)
    if path[journey] == 'L':
        myLoc1 = myLoc1.leftChild
    else:
        myLoc1 = myLoc1.rightChild
    steps1 +=1
print(myLoc1.name)
print(steps1)
while(not(myLoc2.name == "ZZZ" or myLoc2.name == "PMZ" or myLoc2.name == "BLZ" or myLoc2.name == "NPZ" or myLoc2.name == "BJZ" or myLoc2.name == "PBZ")):
    journey = steps2%len(path)
    if path[journey] == 'L':
        myLoc2 = myLoc2.leftChild
    else:
        myLoc2 = myLoc2.rightChild
    steps2 +=1
print(myLoc2.name)
print(steps2)

while(not(myLoc3.name == "ZZZ" or myLoc3.name == "PMZ" or myLoc3.name == "BLZ" or myLoc3.name == "NPZ" or myLoc3.name == "BJZ" or myLoc3.name == "PBZ")):
    journey = steps3%len(path)
    if path[journey] == 'L':
        myLoc3 = myLoc3.leftChild
    else:
        myLoc3 = myLoc3.rightChild
    steps3 +=1
print(myLoc3.name)
print(steps3)
while(not(myLoc4.name == "ZZZ" or myLoc4.name == "PMZ" or myLoc4.name == "BLZ" or myLoc4.name == "NPZ" or myLoc4.name == "BJZ" or myLoc4.name == "PBZ")):
    journey = steps4%len(path)
    if path[journey] == 'L':
        myLoc4 = myLoc4.leftChild
    else:
        myLoc4 = myLoc4.rightChild
    steps4 +=1
print(myLoc4.name)
print(steps4)
while(not(myLoc5.name == "ZZZ" or myLoc5.name == "PMZ" or myLoc5.name == "BLZ" or myLoc5.name == "NPZ" or myLoc5.name == "BJZ" or myLoc5.name == "PBZ")):
    journey = steps5%len(path)
    if path[journey] == 'L':
        myLoc5 = myLoc5.leftChild
    else:
        myLoc5 = myLoc5.rightChild
    steps5 +=1
print(myLoc5.name)
print(steps5)
while(not(myLoc6.name == "ZZZ" or myLoc6.name == "PMZ" or myLoc6.name == "BLZ" or myLoc6.name == "NPZ" or myLoc6.name == "BJZ" or myLoc6.name == "PBZ")):
    journey = steps6%len(path)
    if path[journey] == 'L':
        myLoc6 = myLoc6.leftChild
    else:
        myLoc6 = myLoc6.rightChild
    steps6 +=1
print(myLoc6.name)
print(steps6)


import math
inter1 = np.lcm(steps1,steps2)

inter2 = np.lcm(steps3,steps4)
inter3 = np.lcm(steps5,steps6)
inter4 = np.lcm(inter1,inter2)
value = np.lcm(inter3,inter4)
print(value)
print(value & 0xffffffff)

print(hex(value))
print(np.lcm.reduce([steps1,steps2,steps3,steps4,steps5,steps6]))
print(math.lcm(steps1,steps2,steps3,steps4,steps5,steps6))

